# Generated by Django 4.1.1 on 2022-11-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='DiseaseType',
        ),
    ]
